config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :tags
    resources :articles
    resources :articles_tags
    resources :archives
  end

  devise_for :users, path: :admin, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
       }

  get '/' => 'index#index'
  get 'entry/:slung' => 'index#show'
  get 'archive/:id' => 'archive#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :archive
  has_many :articles_tags
  has_and_belongs_to_many :tags
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_article_path, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:id, :title, :text, :status, :slung, :picture, :archive_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :id %>
    <% if @article.id.nil? %>
      <%= form.text_field :id, value: "#{Article.last.id +=1}" %>
    <% else %>
      <%= form.text_field :id %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :slung %>
    <%= form.text_field :slung %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :archive_id %>
    <% if @article.archive_id.nil? %>
      <%= form.text_field :archive_id, value: "#{Time.month}" %>
    <% else %>
      <%= form.text_field :archive_id %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<p id="notice"><%= notice %></p>
<main>
<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Text</th>
      <th>Status</th>
      <th>Slung</th>
      <th>Picture</th>
      <th>外部キー</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td class="text"><%= article.text %></td>
        <td><%= article.status %></td>
        <td><%= article.slung %></td>
        <td><%= article.picture %></td>
        <td><%= article.archive_id %></td>
        <td><%= link_to 'Show', [:admin, article] %></td>
        <td><%= link_to 'Edit', edit_admin_article_path(article) %></td>
        <td><%= link_to 'Destroy', [:admin, article], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_admin_article_path %>
</main>
<%= render '/admin/side' %>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p class="large">
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Status:</strong>
  <%= @article.status %>
</p>

<p>
  <strong>Slung:</strong>
  <%= @article.slung %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @article.picture %>
</p>

<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>