config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :tags
    resources :articles
    resources :articles_tags
    resources :archives
  end

  devise_for :users, path: :admin, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
       }

  get '/' => 'index#index'
  get 'entry/:slung' => 'index#show'
  get 'archive/:id' => 'archive#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :articles_tags
  has_and_belongs_to_many :articles
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_tags_path, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_tag_path, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to admin_tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/tags/_form.html.erb
<%= form_for [:admin, @tag] do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <% if @tag.id.nil? %>
      <%= form.text_field :id, value: "#{Tag.last.id +=1}" %>
    <% else %>
      <%= form.text_field :id%>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', admin_tags_path %>

app/views/admin/tags/index.html.erb
<p id="notice"><%= notice %></p>
<main>
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.id %></td>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', [:admin, tag] %></td>
        <td><%= link_to 'Edit', edit_admin_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', [:admin, tag], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_admin_tag_path %>
</main>
<%= render '/admin/side' %>

app/views/admin/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', admin_tags_path %>

app/views/admin/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_admin_tag_path(@tag) %> |
<%= link_to 'Back', admin_tags_path %>