config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :tags
    resources :articles
    resources :articles_tags
    resources :archives
  end

  devise_for :users, path: :admin, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
       }

  get '/' => 'index#index'
  get 'entry/:slung' => 'index#show'
  get 'archive/:id' => 'archive#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/articles_tag.rb
class ArticlesTag < ApplicationRecord
  belongs_to :article, optional: true
  belongs_to :tag, optional: true
end

app/controllers/admin/articles_tags_controller.rb
class Admin::ArticlesTagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_articles_tag, only: [:show, :edit, :update, :destroy]

  # GET /articles_tags
  # GET /articles_tags.json
  def index
    @articles_tags = ArticlesTag.all
  end

  # GET /articles_tags/1
  # GET /articles_tags/1.json
  def show
  end

  # GET /articles_tags/new
  def new
    @articles_tag = ArticlesTag.new
  end

  # GET /articles_tags/1/edit
  def edit
  end

  # POST /articles_tags
  # POST /articles_tags.json
  def create
    @articles_tag = ArticlesTag.new(articles_tag_params)

    respond_to do |format|
      if @articles_tag.save
        format.html { redirect_to admin_articles_tags_path, notice: 'Articles tag was successfully created.' }
        format.json { render :show, status: :created, location: @articles_tag }
      else
        format.html { render :new }
        format.json { render json: @articles_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles_tags/1
  # PATCH/PUT /articles_tags/1.json
  def update
    respond_to do |format|
      if @articles_tag.update(articles_tag_params)
        format.html { redirect_to admin_articles_tag_path, notice: 'Articles tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @articles_tag }
      else
        format.html { render :edit }
        format.json { render json: @articles_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles_tags/1
  # DELETE /articles_tags/1.json
  def destroy
    @articles_tag.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_tags_url, notice: 'Articles tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articles_tag
      @articles_tag = ArticlesTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articles_tag_params
      params.require(:articles_tag).permit(:article_id, :tag_id)
    end
end

app/helpers/articles_tags_helper.rb
module ArticlesTagsHelper
end

app/views/admin/articles_tags/_form.html.erb
<%= form_for [:admin, @articles_tag] do |form| %>
  <% if articles_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articles_tag.errors.count, "error") %> prohibited this articles_tag from being saved:</h2>

      <ul>
      <% articles_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_id %>
    <% if @articles_tag.id.nil? %>
      <%= form.text_field :article_id, value: "#{@articles_tag.last.id +=1}" %>
    <% else %>
      <%= form.text_field :article_id %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.text_field :tag_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles_tags/edit.html.erb
<h1>Editing Articles Tag</h1>

<%= render 'form', articles_tag: @articles_tag %>

<%= link_to 'Back', admin_articles_tags_path %>

app/views/admin/articles_tags/index.html.erb
<p id="notice"><%= notice %></p>
<main>
<h1>Articles Tags</h1>

<table>
  <thead>
    <tr>
      <th>article_id</th>
      <th>tag_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles_tags.each do |articles_tag| %>
      <tr>
        <td><%= articles_tag.article_id %></td>
        <td><%= articles_tag.tag_id %></td>
        <td><%= link_to 'Show', [:admin, articles_tag] %></td>
        <td><%= link_to 'Edit', edit_admin_articles_tag_path(articles_tag) %></td>
        <td><%= link_to 'Destroy', [:admin, articles_tag], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articles Tag', new_admin_articles_tag_path %>
</main>
<%= render '/admin/side' %>

app/views/admin/articles_tags/new.html.erb
<h1>New Articles Tag</h1>

<%= render 'form', articles_tag: @articles_tag %>

<%= link_to 'Back', admin_articles_tags_path %>

app/views/admin/articles_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article_id:</strong>
  <%= @articles_tag.article_id %>
</p>

<p>
  <strong>Tag id:</strong>
  <%= @articles_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_admin_articles_tag_path(@articles_tag) %> |
<%= link_to 'Back', admin_articles_tags_path %>