config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :tags
    resources :articles
    resources :articles_tags
    resources :archives
  end

  devise_for :users, path: :admin, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
       }

  get '/' => 'index#index'
  get 'entry/:slung' => 'index#show'
  get 'archive/:id' => 'archive#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/archive.rb
class Archive < ApplicationRecord
  has_many :articles
end

app/controllers/admin/archives_controller.rb
class Admin::ArchivesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to admin_archives, notice: 'Archive was successfully created.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to [:admin, @archive], notice: 'Archive was successfully updated.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to admin_archives_url, notice: 'Archive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:id, :month, :year)
    end
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  layout 'index'
  def show
    @archives = Archive.all
    @archive = Archive.find(params[:id])
  end
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/admin/archives/_form.html.erb
<%= form_for [:admin, @archive] do |form| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <% if @archive.id.nil? %>
      <%= form.text_field :id, value: "#{Archive.last.id +=1}" %>
      <% else %>
      <%= form.text_field :id %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.text_field :month %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Show', [:admin, @archive] %> |
<%= link_to 'Back', admin_archives_path %>

app/views/admin/archives/index.html.erb
<p id="notice"><%= notice %></p>
<main>
<h1>Archives</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Month</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.id %></td>
        <td><%= archive.month %></td>
        <td><%= archive.year %></td>
        <td><%= link_to 'Show', [:admin, archive] %></td>
        <td><%= link_to 'Edit', edit_admin_archive_path(archive) %></td>
        <td><%= link_to 'Destroy', [:admin, archive], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive', new_admin_archive_path %>
</main>
<%= render '/admin/side' %>

app/views/admin/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Back', admin_archives_path %>

app/views/admin/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @archive.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @archive.year %>
</p>

<%= link_to 'Edit', edit_admin_archive_path(@archive) %> |
<%= link_to 'Back', admin_archives_path %>